name: Scheduled Job
env: 
  MASTODON_ACCESS_TOKEN: ${{ secrets.MASTODON_ACCESS_TOKEN }}
  MASTODON_API_BASE_URL: https://botsin.space/

on:
    schedule:
    - cron: "0 13 * * 1"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Run 
      run: make run
